name: Create Docker Image Job

on:
  workflow_call:
    inputs:
      input-1:
        required: true
        type: string
#    secrets:

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    name: Create Docker Image
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - run: bats -v
